### PR TITLE
Issues/172 add custom notification support

### PR DESCRIPTION
**Pull request by insanoid**

### CODE REVIEW

**Comment by insanoid** [comment]
## HOW TO QA
- The required type notification was removed.
- Please check passing deep-linking elements and urls with the messages.
- Also check referral deep-linking in general.

**Comment by marcelpinto** [comment]
:+1:

**Comment by GrayedFox** [comment]
# QA FAILED

Unfortunately this is a fail - the deep linking is not tracking in Mixpanel.
- **Device/Browser:** iPad Air (8.3), iPhone 5C (8.0.2)
- **Version/URL:** 1.5.0 (99)
- **Reproduction Steps:**
  1. Create a push notification with a deep link (internal or external). Internal deep link found [here](https://docs.google.com/a/eatfirst.com/document/d/173H_pcW8D4MBVNJVPZoliOAMZmiliKnF1FOd_rSquXQ/edit?usp=sharing): 
  2. Open the app and wait for push
  3. Make sure to hit the button (not the cross) in the corner
  4. Make sure the deep link works (you are taken to a web page or to a page within the app)
  5. On MixPanel click on the Analytics link (on the right, near the Push Message) to open the analysis pane
  6. Choose 'DEEP_LINK' for the intended action after a message was sent
- **Result:** No data will be shown here, despite clicking the OK button and the deep link working correctly
- **Expected Result:**
  Make sure to send this info to MP

**Comment by GrayedFox** [comment]
# QA PASSED
- **Device/Browser:** iPad Air (8.3), iPhone 5C (8.0.2)
- **Version/URL:** 1.5.0 (99)
- **Description:** It tracked. It just took AGES. Sorry.

**Pull request merged**
